# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Travis Liang
title: Software Developer
email: travisliang001@gmail.com
phone: 626-376-0850
website: https://travisliang001.github.io/online-cv/

# Social links

github_username:  travisliang001
linkedin_username: jcliang


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/fullsizeoil_profile_photo2-426-edit-edit_002.JPG
about_content: | # this will include new lines to allow paragraphs
 Greetings! I am Travis, a Software Developer based in the sunny city of Los Angeles, CA.
 I have a relentless passion for learning new technology and leveraging it to solve complex problems. I am constantly seeking to expand my skill set and thrive on collaborating with like-minded individuals on creative projects. In addition to my software expertise, I also have a green thumb for gardening and a knack for making mouth-watering sushi! Currently, I am pursuing a Master's degree in Computer Science at the Georgia Institute of Technology.

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
# more_content: | # this will include new lines to allow paragraphs
#   Love basketball, music, anime, also a HardCore Gamer, interested in everything that might interesting, people empathy oriented.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
